#pragma once

#ifndef STRINGIFY
  #define STRINGIFY(x) #x
#endif
#ifndef TOSTRING
  #define TOSTRING(x) STRINGIFY(x)
#endif
#ifndef PROTOCOL_VERSION_MAJOR
  #define PROTOCOL_VERSION_MAJOR 0
#endif
#ifndef PROTOCOL_VERSION_MINOR
  #define PROTOCOL_VERSION_MINOR 18
#endif
#ifndef PROTOCOL_VERSION
  #define PROTOCOL_VERSION "#" TOSTRING(PROTOCOL_VERSION_MAJOR) "." TOSTRING(PROTOCOL_VERSION_MINOR)
#endif
const uint8_t CONST_PROTOCOL_VERSION_MAJOR = PROTOCOL_VERSION_MAJOR;
const uint8_t CONST_PROTOCOL_VERSION_MINOR = PROTOCOL_VERSION_MINOR;